name: network_checker
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  connectivity_plus: ^6.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  scope_provider:
    path: packages/scope_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


